name: buildUp

on:
  push:
    branches:
      - master

jobs:
  build_test_push:

    runs-on: ubuntu-20.04

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      - name: Log in to docker
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Push to Docker Hub
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: softwarelseorg/sherie-portfolio:latest,softwarelseorg/sherie-portfolio:${{ github.sha }}
      - name: deploy to cluster
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
        with:
          args: --namespace sherie set image deployment/sherie-portfolio sherie-portfolio=softwarelseorg/sherie-portfolio:latest
      - name: verify deployment
        uses: steebchen/kubectl@master
        env:
          KUBE_CONFIG_DATA: ${{ secrets.KUBE_CONFIG_DATA }}
          KUBECTL_VERSION: "1.15"
        with:
          args: --namespace sherie rollout status deployment/sherie-portfolio
